(define (next-coin coin)
    (cond((= coin 15) 10)
        ((= coin 10) 5)
        ((= coin 5) 3)
        ((= coin 3) 2)
        ((= coin 2) 1)
        ((or (not(= coin 15)) (not(= coin 10)) (not(= coin 5)) (not(= coin 3)) (not(= coin 2))) 0)
    )
)