# Generated by Django 3.0 on 2021-11-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('family', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('count_wons', models.PositiveIntegerField()),
                ('sex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('players', models.ManyToManyField(to='tennis_application.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('begin_tur', models.DateTimeField()),
                ('end_tur', models.DateTimeField()),
                ('category', models.CharField(max_length=15)),
                ('players', models.ManyToManyField(to='tennis_application.Player')),
                ('sponsors', models.ManyToManyField(to='tennis_application.Sponsor')),
            ],
        ),
    ]
